<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5bc2b3204ce5d',
	'title' => '各車種設定',
	'fields' => array(
		array(
			'key' => 'field_5bdfaf5eb54fe',
			'label' => '各ページ共通 バナー画像',
			'name' => 'cartype_stylewagon_image',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5bcae33562247',
			'label' => '各車種ページ設定',
			'name' => 'cartype_stylewagon_post',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => '指定車種の記事を追加',
			'sub_fields' => array(
				array(
					'key' => 'field_5bcae41f62248',
					'label' => '車種記事タイトル',
					'name' => 'cartype_stylewagon_post_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5bcae45662249',
					'label' => '車種記事本文',
					'name' => 'cartype_stylewagon_post_content',
					'type' => 'textarea',
					'instructions' => 'ここには本文の最初の100文字程度を入力してください。表示は自動で調整されます。',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => '',
					'new_lines' => '',
				),
				array(
					'key' => 'field_5bcae4846224a',
					'label' => '車種記事アイキャッチ画像',
					'name' => 'cartype_stylewagon_post_image_url',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5bcae4d36224b',
					'label' => '車種記事URL',
					'name' => 'cartype_stylewagon_post_url',
					'type' => 'url',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
				),
			),
		),
		array(
			'key' => 'field_5bd7c179b5b4f',
			'label' => 'スタイルワゴン 関連記事総数',
			'name' => 'car_related_articles',
			'type' => 'number',
			'instructions' => '「スタイルワゴン・ドレスアップナビ」での車種に関連する記事すべての数を入力してください。関連記事はどんどん増えていきますので正確に入れる必要はなく、ざっくり10記事単位くらいで十分です。',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '記事以上！',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5bc2b41800bd0',
			'label' => '各車種パーツカテゴリーページ設定',
			'name' => 'tax_part_type_setting',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'row',
			'button_label' => 'カテゴリーページ設定を追加',
			'sub_fields' => array(
				array(
					'key' => 'field_5bc2b4b000bd1',
					'label' => 'パーツカテゴリー',
					'name' => 'part_type',
					'type' => 'taxonomy',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'taxonomy' => 'part-type',
					'field_type' => 'select',
					'allow_null' => 0,
					'add_term' => 1,
					'save_terms' => 0,
					'load_terms' => 0,
					'return_format' => 'id',
					'multiple' => 0,
				),
				array(
					'key' => 'field_5bc2b5c900bd2',
					'label' => 'スタイルワゴン 指定カテゴリ記事',
					'name' => 'stylewagon_post',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => '指定カテゴリ記事を追加',
					'sub_fields' => array(
						array(
							'key' => 'field_5bc98cf0517f4',
							'label' => '指定カテゴリ記事タイトル',
							'name' => 'stylewagon_post_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5bc98d0f517f5',
							'label' => '指定カテゴリ記事本文',
							'name' => 'stylewagon_post_content',
							'type' => 'textarea',
							'instructions' => 'ここには本文の最初の100文字程度を入力してください。表示は自動で調整されます。',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'new_lines' => '',
						),
						array(
							'key' => 'field_5bc98d71517f6',
							'label' => '指定カテゴリ記事アイキャッチ画像',
							'name' => 'stylewagon_post_image_url',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'url',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_5bc98db4517f7',
							'label' => '指定カテゴリ記事URL',
							'name' => 'stylewagon_post_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_5bc2b63500bd3',
					'label' => 'スタイルワゴン 指定カテゴリ一覧ページ',
					'name' => 'stylewagon_archive',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'collapsed' => '',
					'min' => 0,
					'max' => 0,
					'layout' => 'row',
					'button_label' => 'カテゴリ一覧ページを追加',
					'sub_fields' => array(
						array(
							'key' => 'field_5bd7e93db5b51',
							'label' => '指定カテゴリ名',
							'name' => 'stylewagon_category_name',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5bd7e917b5b50',
							'label' => '指定カテゴリ一覧ページURL',
							'name' => 'stylewagon_archive_url',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5bd7e966b5b52',
							'label' => '指定カテゴリ 記事総数',
							'name' => 'category_related_articles',
							'type' => 'number',
							'instructions' => '「スタイルワゴン・ドレスアップナビ」での車種に関連する記事すべての数を入力してください。関連記事はどんどん増えていきますので正確に入れる必要はなく、ざっくり10記事単位くらいで十分です。ここは空欄でも大丈夫です。',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '記事以上！',
							'min' => '',
							'max' => '',
							'step' => '',
						),
					),
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-car.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;
